/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TAM_MSG 300

typedef char *msg_error;
#define TAM_EXPR_MATEMATICA 1000

typedef char *expr_mat;

struct calc_res {
	int error;
	union {
		double resultado;
		msg_error msg_error;
	} calc_res_u;
};
typedef struct calc_res calc_res;

#define CALCULADORA 0x20000001
#define CALC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULA 1
extern  calc_res * calcula_1(expr_mat , CLIENT *);
extern  calc_res * calcula_1_svc(expr_mat , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULA 1
extern  calc_res * calcula_1();
extern  calc_res * calcula_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg_error (XDR *, msg_error*);
extern  bool_t xdr_expr_mat (XDR *, expr_mat*);
extern  bool_t xdr_calc_res (XDR *, calc_res*);

#else /* K&R C */
extern bool_t xdr_msg_error ();
extern bool_t xdr_expr_mat ();
extern bool_t xdr_calc_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
