/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>

calc_res calculadora_1(char *host, char *expr_matematica)
{
	const char *TRANSPORTE = "tcp";
	CLIENT *clnt;
	calc_res *resultado;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALC_VER, TRANSPORTE);
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(EXIT_FAILURE);
	}
#endif /* DEBUG */

	resultado = calcula_1(expr_matematica, clnt);
	if (resultado == (calc_res *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	return (*resultado);
}

void elimina_blancos(char * cadena)
{
	int i, j;
	i = 0;
	j = 0;

	while (cadena[i] != '\0')
	{
		if (!isspace(cadena[i]))
		{
			cadena[j] = cadena[i];
			j++;
		}
		i++;
	}

	cadena[j] = '\0';
}

int main(int argc, char *argv[])
{
	char *host;
	char expr_matematica[TAM_EXPR_MATEMATICA];
	calc_res resultado;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	while (fgets(expr_matematica, TAM_EXPR_MATEMATICA, stdin))
	{
		elimina_blancos(expr_matematica);
		// printf("%s", expr_matematica);
		resultado = calculadora_1(host, expr_matematica);

		if (resultado.error == 1)
		{
			printf("%s\n\n", resultado.calc_res_u.msg_error);
		}
		else
		{
			printf("= %lf\n\n", resultado.calc_res_u.resultado);
		}
	}

	exit(EXIT_SUCCESS);
}
