/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_msg_error (XDR *xdrs, msg_error *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAM_MSG))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_expr_mat (XDR *xdrs, expr_mat *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAM_EXPR_MATEMATICA))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_calc_res (XDR *xdrs, calc_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_double (xdrs, &objp->calc_res_u.resultado))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_msg_error (xdrs, &objp->calc_res_u.msg_error))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
